### ISSUE TITLE
Reanalysis doesn't work when BST is in the date time in the analysis log

### ISSUE THREAD

**Issue by grovesn** [sch-sdgs/SDGSPipeline#83]
Originally run on v3.1.4, analysis log has BST in the date time values (before year). Error is the following:

Traceback (most recent call last):
  File "/results/Pipeline/SDGSPipeline/scripts/reanalysis_helper.py", line 48, in <module>
    main()
  File "/results/Pipeline/SDGSPipeline/scripts/reanalysis_helper.py", line 16, in main
    ngs_patient = f.parse_analysis_log(args.analysis_log)
  File "/home/bioinfo/mparker/virtualenvs/sdgs/local/lib/python2.7/site-packages/helpers/FileParsers.py", line 530, in parse_analysis_log
    start_tuple = time.strptime(start_string, '%Y-%b-%d %H:%M:%S')
  File "/usr/lib/python2.7/_strptime.py", line 454, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'BST-Apr- 3' does not match format '%Y-%b-%d %H:%M:%S'

**Comment by grovesn** [comment]
This is due to single digit dates not BST. When the date is <10, an additional space is used for padding and this alters the indexes for finding the relevant fields in the date string.
